### ISSUE TITLE
Parse error on forbidden line query

### ISSUE THREAD

**Issue by spacemansteve** [romanchyla/montysolr#159]
A query like C[II] results in a 500 error.
This notation is used [forbidden line](https://en.wikipedia.org/wiki/Forbidden_mechanism).  Perhaps Solr is expecting [x TO y]?  Semi-forbidden lines only use the close square bracket, they are much more rare.

Solr log says: null:java.lang.ClassCastException

**Comment by spacemansteve** [comment]
stacktrace from solr log:
```null:java.lang.ClassCastException: org.apache.lucene.queryparser.flexible.aqp.nodes.AqpFunctionQueryNode cannot be cast to org.apache.lucene.queryparser.flexible.core.nodes.FieldVal\
uePairQueryNode
	at org.apache.lucene.queryparser.flexible.standard.nodes.AbstractRangeQueryNode.getLowerBound(AbstractRangeQueryNode.java:101)
	at org.apache.lucene.queryparser.flexible.standard.nodes.AbstractRangeQueryNode.getField(AbstractRangeQueryNode.java:59)
	at org.apache.lucene.queryparser.flexible.standard.processors.LegacyNumericRangeQueryNodeProcessor.postProcessNode(LegacyNumericRangeQueryNodeProcessor.java:73)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89)
	at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250)
	at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
	at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:358)
	at org.apache.solr.search.QParser.getQuery(QParser.java:140)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by spacemansteve** [comment]
Do we want to fix the problem [here] (https://github.com/romanchyla/montysolr/blob/master/contrib/adsabs/src/java/org/apache/solr/search/AqpAdsabsQParser.java#L358) by adding another catch clause for ClassCastException?

**Comment by romanchyla** [comment]
We want to fix the underlaying cause, something is expecting certain query tree type, and it's not there. Perhaps it is the range query that could detect forbidden lines and not create range qtype

**Comment by spacemansteve** [comment]
Forbidden line queries currently return a 500.  My immediate goal was to convert that to a 400.  If we change the code generate something more appropriate than a range qtype will the search work well or do we need to also coordinate changes during indexing and to fulltext?  Should a functional forbidden line query be the goal of this issue?

**Comment by romanchyla** [comment]
we could wrap the main entry point and always return 400; but that's not as useful as actually fixing the problem - so yes, fixing the forbidden line should be the goal (the fact that it parses means no need to be done on the syntax level - otherwise my recommendation would be to generate an error; that is much harder)

**Comment by spacemansteve** [comment]
The query tree is created in org.apache.lucene.queryparser.flexible.core.QueryParserHelper.  It is called from [AqpAdsabsQParser](https://github.com/romanchyla/montysolr/blob/master/contrib/adsabs/src/java/org/apache/solr/search/AqpAdsabsQParser.java#L358).  Assuming we don't want to change lucene/solr code, we need to make our changes in AqpAdsabsQParser. 
One option is to see if passed query looks like a forbidden line query (e.g., has square brackets surrounding a roman numeral).  If it does, we must treat it differently.  Specifically, we can quote the special symbols.

**Comment by romanchyla** [comment]
these are the classes where one should be looking first:

```org.apache.lucene.queryparser.flexible.aqp.nodes.AqpFunctionQueryNode cannot be cast to org.apache.lucene.queryparser.flexible.core.nodes.FieldVal\
uePairQueryNode
	at org.apache.lucene.queryparser.flexible.standard.nodes.AbstractRangeQueryNode.getLowerBound(AbstractRangeQueryNode.java:101)
	at org.apache.lucene.queryparser.flexible.standard.nodes.AbstractRangeQueryNode.getField(AbstractRangeQueryNode.java:59)
	at org.apache.lucene.queryparser.flexible.standard.processors.LegacyNumericRangeQueryNodeProcessor.postProcessNode(LegacyNumericRangeQueryNodeProcessor.java:73)
	```

**Comment by spacemansteve** [comment]
The source files for AbstractRangeQueryNode and LegacyNumericRangeQueryNodeProcessor are not in the montysolr repo (they are downloaded with solr 6.3).   Should we make our changes further up the stack in source files in the montysolr repo?
