### ISSUE TITLE
span converter error

### ISSUE THREAD

**Issue by romanchyla** [romanchyla/montysolr#43]
```
INFO  - 2016-05-05 11:18:57.425; org.apache.solr.core.SolrCore; [collection1] webapp=/solr path=/select params={hl=true&hl.requi
reFieldMatch=true&fl=title,abstract,bibcode,author,keyword,id,links_data,property,citation_count,[citations],pub,aff,email,volum
e,pubdate,doi&hl.usePhraseHighlighter=true&start=25&__fetch_missing=true&sort=date+desc&rows=25&q=++author:"^Takeuchi"+year:2001
&hl.maxAnalyzedChars=150000&hl.q=author:"^Takeuchi"+year:2001&hl.fl=title,abstract,body,ack&wt=json} hits=67 status=0 QTime=257 
INFO  - 2016-05-05 11:18:57.900; org.apache.solr.core.SolrCore; [collection1] webapp=/solr path=/select params={q=++author:"^Takeuchi"+year:2001&facet.pivot=property,year&fl=id&facet.minCount=1&sort=date+desc&facet=true&wt=json} hits=67 status=0 QTime=11 
ERROR - 2016-05-05 11:18:58.000; org.apache.solr.common.SolrException; java.lang.NullPointerException
        at org.apache.lucene.queryparser.flexible.aqp.builders.SpanConverter.convertBooleanToSpan(SpanConverter.java:132)
        at org.apache.lucene.queryparser.flexible.aqp.builders.SpanConverter.getSpanQuery(SpanConverter.java:61)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpAdsabsSubQueryProvider$15.parse(AqpAdsabsSubQueryProvider.java:373)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:30)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:13)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:20)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:10)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:186)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:125)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:118)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:118)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:218)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:69)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:35)
        at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:258)
:
```

**Comment by romanchyla** [comment]
fixed
