### ISSUE TITLE
TokenStream contract violotation: close() call missing

### ISSUE THREAD

**Issue by romanchyla** [romanchyla/montysolr#67]
```
2017-04-28 18:16:35.222 INFO  (qtp26117480-231) [   x:collection1] o.a.s.c.S.Request [collection1]  webapp=/solr path=/select params={facet.limit=20&q=full:"HD149757"+++++author:"^
Lambert"&facet.field=author_facet_hier&fl=id&facet.prefix=0/&sort=date+desc,+bibcode+desc&facet.mincount=1&rows=1&facet=true&wt=json&facet.offset=0} status=500 QTime=3
```

```
2017-04-28 18:16:35.222 ERROR (qtp26117480-231) [   x:collection1] o.a.s.h.RequestHandlerBase java.lang.IllegalStateException: TokenStream contract violation: close() call missing
        at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
        at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:412)
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:165)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.getSynonyms(AqpAdsabsExpandAuthorSearchProcessor.java:251)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.doExpansion(AqpAdsabsExpandAuthorSearchProcessor.java:149)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.expandNodes(AqpAdsabsExpandAuthorSearchProcessor.java:118)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.postProcessNode(AqpAdsabsExpandAuthorSearchProcessor.java:77)
        at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98)
        at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.process(AqpAdsabsExpandAuthorSearchProcessor.java:55)
        at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89)
        at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250)
        at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
        at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
        at org.apache.solr.search.QParser.getQuery(QParser.java:140)
        at org.apache.solr.search.AqpFunctionQParser.parseNestedQuery(AqpFunctionQParser.java:159)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpAdsabsSubQueryProvider$15.parse(AqpAdsabsSubQueryProvider.java:348)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:30)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:13)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:20)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:10)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:185)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:124)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:117)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:117)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:217)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:69)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:35)
        at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:253)
        at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
        at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
        at org.apache.solr.search.QParser.getQuery(QParser.java:140)
        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
```

**Comment by romanchyla** [comment]
it seems as if one of the threads is sick, I can trigger the problem 1/3 times: but logs don't really show any other error

```
[root@ip-10-1-1-189 ec2-user]# curl 'http://localhost:80/solr/collection1/select?facet.limit=20&q=full:"HD149757"+++++author:"^Lambert"&facet.field=author_facet_hier&fl=id&facet.prefix=0/&sort=date+desc,+bibcode+desc&facet.mincount=1&rows=1&facet=true&wt=json&facet.offset=0'
{"responseHeader":{"status":0,"QTime":4,"params":{"facet.limit":"20","q":"full:\"HD149757\"     author:\"^Lambert\"","facet.field":"author_facet_hier","fl":"id","facet.prefix":"0/","sort":"date desc, bibcode desc","facet.mincount":"1","rows":"1","facet":"true","wt":"json","facet.offset":"0"}},"response":{"numFound":0,"start":0,"docs":[]},"facet_counts":{"facet_queries":{},"facet_fields":{"author_facet_hier":[]},"facet_ranges":{},"facet_intervals":{},"facet_heatmaps":{}}}
[root@ip-10-1-1-189 ec2-user]# curl 'http://localhost:80/solr/collection1/select?facet.limit=20&q=full:"HD149757"+++++author:"^Lambert"&facet.field=author_facet_hier&fl=id&facet.prefix=0/&sort=date+desc,+bibcode+desc&facet.mincount=1&rows=1&facet=true&wt=json&facet.offset=0'
{"responseHeader":{"status":500,"QTime":3,"params":{"facet.limit":"20","q":"full:\"HD149757\"     author:\"^Lambert\"","facet.field":"author_facet_hier","fl":"id","facet.prefix":"0/","sort":"date desc, bibcode desc","facet.mincount":"1","rows":"1","facet":"true","wt":"json","facet.offset":"0"}},"error":{"msg":"TokenStream contract violation: close() call missing","trace":"java.lang.IllegalStateException: TokenStream contract violation: close() call missing\n\tat org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)\n\tat org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:412)\n\tat org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:165)\n\tat org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.getSynonyms(AqpAdsabsExpandAuthorSearchProcessor.java:251)\n\tat org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.doExpansion(AqpAdsabsExpandAuthorSearchProcessor.java:149)\n\tat org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.expandNodes(AqpAdsabsExpandAuthorSearchProcessor.java:118)\n\tat org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.postProcessNode(AqpAdsabsExpandAuthorSearchProcessor.java:77)\n\tat org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98)\n\tat org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89)\n\tat org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.process(AqpAdsabsExpandAuthorSearchProcessor.java:55)\n\tat org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89)\n\tat org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250)\n\tat org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)\n\tat org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:140)\n\tat org.apache.solr.search.AqpFunctionQParser.parseNestedQuery(AqpFunctionQParser.java:159)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpAdsabsSubQueryProvider$15.parse(AqpAdsabsSubQueryProvider.java:348)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:30)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:13)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:20)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:10)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:185)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:124)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:117)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:117)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:217)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:69)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:35)\n\tat org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:253)\n\tat org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)\n\tat org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:140)\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:518)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)\n\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)\n\tat java.lang.Thread.run(Thread.java:748)\n","code":500}}
```

**Comment by romanchyla** [comment]
these are all the available errors that preceded the close() call:

```
/media/shared_folder/logs/solr.log.3:2017-04-28 11:06:49.405 ERROR (qtp26117480-231) [   x:collection1] o.a.s.s.HttpSolrCall null:java.lang.IllegalStateException: TokenStream contract violation: close() call missing
/media/shared_folder/logs/solr.log.4:2017-04-28 01:09:33.809 ERROR (qtp26117480-87) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: The query is empty
/media/shared_folder/logs/solr.log.5:2017-04-27 20:26:00.542 ERROR (qtp26117480-411) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: INVALID_SYNTAX_CANNOT_PARSE: Syntax Error, cannot parse author:"^Madau" bibstem:"": The parser reported a syntax error, antlrqueryparser hates errors! 
/media/shared_folder/logs/solr.log.5:2017-04-27 21:01:40.855 ERROR (searcherExecutor-7-thread-1-processing-x:collection1) [   x:collection1] o.a.s.s.CitationLRUCache Field alternate_bibcode has no schema entry; skipping it!
/media/shared_folder/logs/solr.log.5:2017-04-27 21:11:38.824 ERROR (searcherExecutor-7-thread-1-processing-x:collection1) [   x:collection1] o.a.s.s.CitationLRUCache Field citation has no schema entry; skipping it!
/media/shared_folder/logs/solr.log.5:2017-04-27 23:25:41.361 ERROR (qtp26117480-87) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: INVALID_SYNTAX_CANNOT_PARSE: Syntax Error, cannot parse author:"Katkov, I. Yu." not author:"Campbell" not author:Ulrich": The parser reported a syntax error, antlrqueryparser hates errors! 
/media/shared_folder/logs/solr.log.6:2017-04-27 15:48:27.215 ERROR (searcherExecutor-7-thread-1-processing-x:collection1) [   x:collection1] o.a.s.s.CitationLRUCache Field alternate_bibcode has no schema entry; skipping it!
/media/shared_folder/logs/solr.log.6:2017-04-27 15:56:03.791 ERROR (searcherExecutor-7-thread-1-processing-x:collection1) [   x:collection1] o.a.s.s.CitationLRUCache Field citation has no schema entry; skipping it!
/media/shared_folder/logs/solr.log.6:2017-04-27 16:15:09.172 ERROR (qtp26117480-165) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
/media/shared_folder/logs/solr.log.6:2017-04-27 16:15:09.173 ERROR (qtp26117480-165) [   x:collection1] o.a.s.s.HttpSolrCall null:org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
/media/shared_folder/logs/solr.log.6:2017-04-27 16:38:33.706 ERROR (qtp26117480-231) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: INVALID_SYNTAX_CANNOT_PARSE: Syntax Error, cannot parse  full:"m4ast" =: The parser reported a syntax error, antlrqueryparser hates errors! 
/media/shared_folder/logs/solr.log.6:2017-04-27 17:44:43.459 ERROR (qtp26117480-269) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: The query is empty
/media/shared_folder/logs/solr.log.6:2017-04-27 17:44:43.464 ERROR (qtp26117480-442) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: The query is empty
/media/shared_folder/logs/solr.log.6:2017-04-27 18:26:10.082 ERROR (qtp26117480-411) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: COULD_NOT_PARSE_NUMBER: Could not parse text "1987" using org.apache.solr.search.AqpAdsabsQParser.MaxNumberFormat
/media/shared_folder/logs/solr.log.6:2017-04-27 18:27:59.015 ERROR (qtp26117480-91) [   x:collection1] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: org.apache.solr.common.SolrException: undefined field fulltext

```

**Comment by taylorshaulis** [comment]
This was observed again today

```
2017-05-17 14:27:12.194 ERROR (qtp26117480-373) [   x:collection1] o.a.s.s.HttpSolrCall null:java.lang.IllegalStateException: TokenStream contract violation: close() call missing
	at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
	at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:412)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:165)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.getSynonyms(AqpAdsabsExpandAuthorSearchProcessor.java:251)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.doExpansion(AqpAdsabsExpandAuthorSearchProcessor.java:149)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.expandNodes(AqpAdsabsExpandAuthorSearchProcessor.java:98)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.doExpansion(AqpAdsabsExpandAuthorSearchProcessor.java:235)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.expandNodes(AqpAdsabsExpandAuthorSearchProcessor.java:98)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.postProcessNode(AqpAdsabsExpandAuthorSearchProcessor.java:77)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.process(AqpAdsabsExpandAuthorSearchProcessor.java:55)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89)
	at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250)
	at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
	at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
	at org.apache.solr.search.QParser.getQuery(QParser.java:140)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```



To resolve this, I got on the instance having errors and from within the docker executed
stop montysolr
start montysolr


Could have probably just restarted but i wanted to confirm it died and started new.
