### ISSUE TITLE
500 error IllegalStateException: TokenStream contract violation: close() call missing

### ISSUE THREAD

**Issue by taylorshaulis** [romanchyla/montysolr#72]
Finally got an example of a request that worked and suddenly got a 500 error.

Access log from gunicorn

{
  "_index": "cwl-2017.07.25",
  "_type": "staging-adsws-gunicorn-access",
  "_id": "33473209373890800310831453976721692829915553815630708749",
  "_score": null,
  "_source": {
    "referer": "https://devui.adsabs.harvard.edu/",
    "cookie": "-",
    "request_method": "GET",
    "authorization": "Bearer:GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l",
    "response_length": "4532",
    "protocol": "HTTP/1.1",
    "request_time": 22837,
    "URLpath": "/search/query",
    "host": "65.112.8.197, 10.1.0.44",
    "moment_this_happened": "2017-07-25T13:50:20.533Z",
    "status_line": "GET /v1/search/query?facet=true&facet.limit=-1&facet.pivot=property%2Ccitation_count&q=author%3A%22McDonald%2C%20S.%22&sort=date%20asc%2C%20bibcode%20asc&stats=true&stats.field=citation_count HTTP/1.1",
    "query_string": "facet=true&facet.limit=-1&facet.pivot=property%2Ccitation_count&q=author%3A%22McDonald%2C%20S.%22&sort=date%20asc%2C%20bibcode%20asc&stats=true&stats.field=citation_count",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0",
    "status": 500,
    "@id": "33473209373890800310831453976721692829915553815630708749",
    "@timestamp": "2017-07-25T13:50:20.533Z",
    "@message": "\"65.112.8.197, 10.1.0.44\" \"[25/Jul/2017:13:50:20 +0000]\" \"GET /v1/search/query?facet=true&facet.limit=-1&facet.pivot=property%2Ccitation_count&q=author%3A%22McDonald%2C%20S.%22&sort=date%20asc%2C%20bibcode%20asc&stats=true&stats.field=citation_count HTTP/1.1\" \"GET\" \"/search/query\" \"facet=true&facet.limit=-1&facet.pivot=property%2Ccitation_count&q=author%3A%22McDonald%2C%20S.%22&sort=date%20asc%2C%20bibcode%20asc&stats=true&stats.field=citation_count\" \"HTTP/1.1\" \"500\" \"4532\" \"https://devui.adsabs.harvard.edu/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0\" \"22837\" \"-\" \"Bearer:GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l\"",
    "@owner": "084981688622",
    "@log_group": "staging-adsws-gunicorn-access",
    "@log_stream": "aec8e9bcc32a-gunicorn-access"
  },
  "fields": {
    "@timestamp": [
      1500990620533
    ]
  },
  "sort": [
    1500990620533
  ]
}

Error log from solr.log on the searcher

2017-07-25 13:50:20.368 INFO  (qtp26117480-329) [   x:collection1] o.a.s.c.S.Request [collection1]  webapp=/solr path=/select params={q=author:"McDonald,+S."&facet.limit=-1&stats=true&facet.pivot=property,citation_count&fl=id&sort=date+asc
,+bibcode+asc&wt=json&facet=true&stats.field=citation_count} status=500 QTime=0
2017-07-25 13:50:20.368 ERROR (qtp26117480-329) [   x:collection1] o.a.s.s.HttpSolrCall null:java.lang.IllegalStateException: TokenStream contract violation: close() call missing
        at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
        at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:412)
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:165)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAnalyzerQueryNodeProcessor.postProcessNode(AqpAnalyzerQueryNodeProcessor.java:134)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsAnalyzerProcessor.postProcessNode(AqpAdsabsAnalyzerProcessor.java:60)
        at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98)
        at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89)
        at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAnalyzerQueryNodeProcessor.process(AqpAnalyzerQueryNodeProcessor.java:109)
        at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89)
        at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250)
        at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
        at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
        at org.apache.solr.search.QParser.getQuery(QParser.java:140)
        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:518)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)

**Comment by taylorshaulis** [comment]
TokenStream contract violation error has occurred at least 2382 times in the past 24 hours according to solr logs.

**Comment by taylorshaulis** [comment]
About 46124 total requests result in about a 5% error rate to solr for this error alone.

**Comment by taylorshaulis** [comment]
This is still an issue

2017-09-26 19:27:56.679 ERROR (qtp1190524793-332) [   x:collection1] o.a.s.s.HttpSolrCall null:java.lang.IllegalStateException: TokenStream contract violation: close() call missing
	at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
	at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:412)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:165)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.getSynonyms(AqpAdsabsExpandAuthorSearchProcessor.java:251)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.doExpansion(AqpAdsabsExpandAuthorSearchProcessor.java:149)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.expandNodes(AqpAdsabsExpandAuthorSearchProcessor.java:98)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.doExpansion(AqpAdsabsExpandAuthorSearchProcessor.java:235)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.expandNodes(AqpAdsabsExpandAuthorSearchProcessor.java:98)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.postProcessNode(AqpAdsabsExpandAuthorSearchProcessor.java:77)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:98)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processChildren(QueryNodeProcessorImpl.java:124)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.processIteration(QueryNodeProcessorImpl.java:96)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorImpl.process(QueryNodeProcessorImpl.java:89)
	at org.apache.lucene.queryparser.flexible.aqp.processors.AqpAdsabsExpandAuthorSearchProcessor.process(AqpAdsabsExpandAuthorSearchProcessor.java:55)
	at org.apache.lucene.queryparser.flexible.core.processors.QueryNodeProcessorPipeline.process(QueryNodeProcessorPipeline.java:89)
	at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:250)
	at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
	at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
	at org.apache.solr.search.QParser.getQuery(QParser.java:140)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)

**Comment by romanchyla** [comment]
when exception id raised, the close was not called

here is elasticsearch fix: https://github.com/elastic/elasticsearch/pull/13870/files

solr to my knowledge doesnt have it fixed
