### ISSUE TITLE
Exception raised by queries with NEAR operator and the fulltext field

### ISSUE THREAD

**Issue by marblestation** [romanchyla/montysolr#78]
Queries like with the NEAR operator and the fulltext field fail (e.g., full:"frew" NEAR2 full:"j")

```
{'action': 'get',
 'client_data': None,
 'client_headers': {'Authorization': 'Bearer:AMclF1tly4SconGeILvdb3C8guIYmy1XxTS2hFvi'},
 'server_data': {u'error': {u'code': 500,
   u'msg': u'Clauses must have same field.',
   u'trace': u'java.lang.IllegalArgumentException: Clauses must have same field.\n\tat org.apache.lucene.search.spans.SpanOrQuery.addClause(SpanOrQuery.java:60)\n\tat org.apache.lucene.search.spans.SpanOrQuery.<init>(SpanOrQuery.java:51)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.SpanConverter.convertBooleanToSpan(SpanConverter.java:167)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.SpanConverter.getSpanQuery(SpanConverter.java:62)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpNearQueryNodeBuilder.build(AqpNearQueryNodeBuilder.java:80)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:185)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:124)\n\tat org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:217)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:69)\n\tat org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:35)\n\tat org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:253)\n\tat org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)\n\tat org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:140)\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:518)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)\n\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)\n\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)\n\tat java.lang.Thread.run(Thread.java:748)\n'},
  u'responseHeader': {u'QTime': 11,
   u'params': {u'fl': u'title,abstract,bibcode,author,keyword,id,citation_count,[citations],pub,aff,volume,pubdate,doi,pub_raw,page,links_data,property',
    u'hl': u'true',
    u'hl.fl': u'title,abstract,body,ack',
    u'hl.maxAnalyzedChars': u'150000',
    u'hl.q': u'full:"frew" NEAR2 full:"j"',
    u'hl.requireFieldMatch': u'true',
    u'hl.usePhraseHighlighter': u'true',
    u'q': u'full:"frew" NEAR2 full:"j"',
    u'rows': u'25',
    u'sort': u'date desc, bibcode desc',
    u'start': u'0',
    u'wt': u'json'},
   u'status': 500}},
 'server_headers': {'Content-Length': '4722', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, Orcid-Authorization, X-BB-Api-Client-Version, X-CSRFToken', 'Set-Cookie': 'session=.eJyrVopPK0otzlCyKikqTdVRis9MUbKqVlJIUrJSisx1y_QNDzXxDfc19Mvyy_V38TX2C3E19Avxy41yCcrwdY_KicrKNvSt8rVVqgXqLUgtyk3MS80rgZlWWpxaBDZRyVCpFgA30iJ_.DNNXyQ.d_QBpzasGueOM7uaUNodxWSWKWM; Expires=Sun, 26-Nov-2017 11:26:01 GMT; HttpOnly; Path=/', 'Vary': 'Origin', 'Server': 'nginx/1.10.2', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Date': 'Thu, 26 Oct 2017 11:26:01 GMT', 'Access-Control-Allow-Origin': 'http://0.0.0.0:8000, http://hourly.adslabs.org, http://localhost:8000, http://ui.adsabs.harvard.edu, http://ui.adslabs.org, https://devui.adsabs.harvard.edu, https://experimental-bumblebee.us-east-1.elasticbeanstalk.com, https://staging-bumblebee.elasticbeanstalk.com, https://staging-bumblebee.us-east-1.elasticbeanstalk.com, https://ui.adsabs.harvard.edu', 'Access-Control-Allow-Methods': 'DELETE, GET, OPTIONS, POST, PUT', 'Content-Type': 'application/json'},
 'server_status_code': 500,
 'url': u'https://devapi.adsabs.harvard.edu/v1/search/query?hl.requireFieldMatch=true&sort=date+desc%2C+bibcode+desc&hl.q=full%3A%22frew%22+NEAR2+full%3A%22j%22&hl.maxAnalyzedChars=150000&hl=true&hl.fl=title%2Cabstract%2Cbody%2Cack&fl=title%2Cabstract%2Cbibcode%2Cauthor%2Ckeyword%2Cid%2Ccitation_count%2C%5Bcitations%5D%2Cpub%2Caff%2Cvolume%2Cpubdate%2Cdoi%2Cpub_raw%2Cpage%2Clinks_data%2Cproperty%2Cemail&rows=25&q=full%3A%22frew%22+NEAR2+full%3A%22j%22&start=0&hl.usePhraseHighlighter=true'}
```

Better formatted exception trace:

```
java.lang.IllegalArgumentException: Clauses must have same field.
at org.apache.lucene.search.spans.SpanOrQuery.addClause(SpanOrQuery.java:60)
at org.apache.lucene.search.spans.SpanOrQuery.<init>(SpanOrQuery.java:51)
at org.apache.lucene.queryparser.flexible.aqp.builders.SpanConverter.convertBooleanToSpan(SpanConverter.java:167)
at org.apache.lucene.queryparser.flexible.aqp.builders.SpanConverter.getSpanQuery(SpanConverter.java:62)
at org.apache.lucene.queryparser.flexible.aqp.builders.AqpNearQueryNodeBuilder.build(AqpNearQueryNodeBuilder.java:80)
at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:185)
at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:124)
at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:217)
at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:69)
at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:35)
at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:253)
at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
at org.apache.solr.search.QParser.getQuery(QParser.java:140)
at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at org.eclipse.jetty.server.Server.handle(Server.java:518)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by aaccomazzi** [comment]
This also applies to unfielded searches
